fusion_node:
  ros__parameters:
    input:
      topics: [
        "/blueview/points2",
        "/blueview/points2"
      ]
      frame_ids: [
        "blueview",
        "blueview"
      ]
      sync: 
        queue_size: 10  # queue size for message filtering
        slop: 0.1       # seconds for approximate time sync 
    output:
      topic: "/fused_pointcloud"
      frame_id: "fused_frame"
    transform:
      type: "static"  # "static" or "dynamic"