fusion_node:
  ros__parameters:
    message_sync: 
      queue_size: 10
      slop: 0.1
    input_topics: [
      "/blueview/points2",
      "/blueview/points2"
    ]
    output_topic: "/fused_pointcloud"