fusion:
  ros__parameters:
    use_sim_time: false
    input:
      topics: [
          "/your/cloud1", # <-- insert input topic
          "/your/cloud2", # <-- insert input topic
        ]
      frame_ids: [
          "your_frame1", # <-- insert frame ID for cloud1
          "your_frame2", # <-- insert frame ID for cloud2
        ]
      sync:
        queue_size: 20 # queue size for message filtering
        epsilon_ms: 100 # espilon window for approximate input message sync
    output:
      topic: "/fused_pointcloud" # <-- insert desired output topic
      frame_id: "fused_frame" # <-- insert desired output frame ID
    transform:
      type: "static" # "static" or "dynamic" transform lookup
